# docker run --name my-custom-nginx-container -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro \
# -d nginx ningx-debug -g 'daemon off;'

services:
  web:
    image: nginx
    # container_name: my-nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    command: 
      - "nginx-debug"
      - "-g"
      - "daemon off;"